In [3]:
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset,DataLoader
from sklearn.model_selection import train_test_split

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
df = pd.read_csv('/content/drive/MyDrive/Deep Learning/01_ANN/all/Data_set/breast-cancer.csv.xls')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       569 non-null    int64
 1   diagnosis                569 non-null    object
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             569 non-null    float64
 15  area_se                  569 non-null    float64
 16  smoothness_se            569 non-null    float64
 17  compactness_se           569 non-null    float64
 18  concavity_se             569 non-null    float64
 19  concave points_se        569 non-null    float64
 20  symmetry_se              569 non-null    float64
 21  fractal_dimension_se     569 non-null    float64
 22  radius_worst             569 non-null    float64
 23  texture_worst            569 non-null    float64
 24  perimeter_worst          569 non-null    float64
 25  area_worst               569 non-null    float64
 26  smoothness_worst         569 non-null    float64
 27  compactness_worst        569 non-null    float64
 28  concavity_worst          569 non-null    float64
 29  concave points_worst     569 non-null    float64
 30  symmetry_worst           569 non-null    float64
 31  fractal_dimension_worst  569 non-null    float64
dtypes: float64(30), int64(1), object(1)
memory usage: 142.4+ KB

In [7]:
df.shape

(569, 32)

In [8]:
# check the target variable distribution
df['diagnosis'].value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

In [9]:
# Drop id columns
df.drop('id',axis=1,inplace=True)

In [10]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['diagnosis']=le.fit_transform(df['diagnosis'])

In [11]:
X=df.drop('diagnosis',axis=1)
y=df['diagnosis']

In [12]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [13]:
from sklearn.preprocessing import StandardScaler

sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [14]:
df

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,1,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,1,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,1,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,1,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,1,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,1,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,1,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,1,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,0,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

tensor e convert

In [15]:
X_train_tensor = torch.tensor(
    X_train,
    dtype=torch.float32
)

X_test_tensor = torch.tensor(
    X_test,
    dtype=torch.float32
)

y_train_tensor = torch.tensor(
    y_train,
    dtype=torch.float32
).view(-1, 1)

y_test_tensor = torch.tensor(
    y_test.values,
    dtype=torch.float32
).view(-1, 1)

custom data set

In [16]:
class BrestCancerDataset(Dataset):

    def __init__(self, features, labels):

        self.features = torch.tensor(
            features,
            dtype=torch.float32
        )

        self.labels = torch.tensor(
            labels.values,
            dtype=torch.float32
        ).view(-1, 1)

    def __len__(self):
        return len(self.features)

    def __getitem__(self, index):
        return self.features[index], self.labels[index]

In [17]:
train_dataset=BrestCancerDataset(
    X_train,y_train
)

test_dataset=BrestCancerDataset(
    X_test,y_test
)

In [18]:
train_loader = DataLoader(
    train_dataset,
    batch_size = 32,
    shuffle = True
)

test_loader = DataLoader(
    train_dataset,
    batch_size =32,
    shuffle = False
)

Defining model

In [19]:
class mySImpleANN(nn.Module):
  def __init__(self,num_features):
    super().__init__()

    self.model = nn.Sequential(
        nn.Linear(num_features,30),
        nn.ReLU(),
        # nn.Linear(1,20),
        # nn.ReLU(),
        nn.Linear(30,1),
        nn.Sigmoid()
    )

  def forward(self,x):
    return self.model(x
    )

Model, Loss, Optimizer

In [20]:
num_features=X_train.shape[1]
num_features

30

In [21]:
epochs = 100
learning_rate = 0.01

In [22]:
model = mySImpleANN(num_features)
# criterion = nn.BCELoss()
criterion = nn.BCEWithLogitsLoss()
optimizer = optim.Adam(model.parameters(),lr=learning_rate)

training loop

In [23]:
for epoch in range(epochs):
  total_epoch_loss =0

  for batch_features, batch_labels in train_loader:
    #forward
    output = model(batch_features)
    #calculate loss
    loss = criterion(output, batch_labels)
    #back pass
    optimizer.zero_grad()
    loss.backward()
    #update
    optimizer.step()
    total_epoch_loss = total_epoch_loss + loss.item()
avg_loss = total_epoch_loss / len(train_loader)
print(avg_loss)

0.5533068577448527

In [24]:
with torch.no_grad():
    outputs = model(X_test_tensor)

    predicted = (outputs > 0.5).float()

    correct = (predicted == y_test_tensor).sum()

    accuracy = correct / y_test_tensor.shape[0]

print("Accuracy:", accuracy.item() * 100)

Accuracy: 96.49122953414917

In [25]:
# model.eval()

# total = 0
# correct = 0


# with torch.no_grad():
#   for batch_features,batch_labels in test_loader:
#     outputs = model(batch_features)
#     # print(f" outputs {outputs}")
#     _,predicted = torch.max(outputs,1)
#     # print(f"predicted {predicted}")

#     #total
#     total = total + batch_labels.shape[0]

#     correct = correct + (predicted==batch_labels).sum().item()


# print(correct/total)
# # print(f"total number {total}")
# # print(f"correct {correct}")

In [26]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

logistic regression

In [39]:

log_model=LogisticRegression(max_iter=1000, random_state=42)
log_model.fit(X_train,y_train)

LogisticRegression(max_iter=1000, random_state=42)

In [40]:
prediction=log_model.predict(X_test)

In [41]:
accuracy=accuracy_score(y_test,prediction)
print("Accuracy= ",accuracy)

Accuracy=  0.9736842105263158

SVC

In [30]:
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

In [31]:
svc = SVC()
svc.fit(X_train,y_train)

SVC()

In [32]:
prediction = svc.predict(X_test)
accuracy=accuracy_score(y_test,prediction)
print("Accuracy= ",accuracy)

Accuracy=  0.9824561403508771

KNN

In [33]:
knn = KNeighborsClassifier()
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [34]:
predict = knn.predict(X_test)
accuracy=accuracy_score(y_test,predict)
print("Accuracy= ",accuracy)

Accuracy=  0.9473684210526315

XGBOOST

In [49]:

from xgboost import XGBClassifier
xgb = XGBClassifier(n_estimators=100, max_depth=6, learning_rate=0.1,
                             random_state=42, use_label_encoder=False, eval_metric='logloss')
xgb.fit(X_train,y_train)

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:12:59] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=6, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=None,
              num_parallel_tree=None, ...)

In [50]:
y_predict = xgb.predict(X_test)
accuracy = accuracy_score(y_test,y_predict)
accuracy

0.956140350877193

lightgbm

In [47]:
from lightgbm import LGBMClassifier
lgb = LGBMClassifier(n_estimators=100, max_depth=6, learning_rate=0.1,
                               random_state=42, verbose=-1)
lgb.fit(X_train,y_train)

LGBMClassifier(max_depth=6, random_state=42, verbose=-1)

In [48]:
y_pred = lgb.predict(X_test)
accuracy = accuracy_score(y_test,y_pred)
accuracy

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

0.9736842105263158

Random forest

In [45]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=100, max_depth=5, random_state=42, n_jobs=-1)
model.fit(X_train, y_train)

RandomForestClassifier(max_depth=5, n_jobs=-1, random_state=42)

In [46]:
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test,y_pred)
accuracy

0.9649122807017544